apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-frontend
  namespace: softw-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-frontend
  template:
    metadata:
      labels:
        app: microservice-frontend
    spec:
      containers:
        - name: frontend
          image: softw/microservice-frontend:practice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-frontend
  namespace: softw-microservices
spec:
  type: NodePort
  selector:
    app: microservice-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
