server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api-gateway:8080/api/;
    proxy_http_version 1.1;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Idempotency-Key $http_idempotency_key;
    proxy_set_header Host $host;
    proxy_request_buffering off;
  }

  location /uploads/ {
    proxy_pass http://api-gateway:8080/uploads/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
