apiVersion: v1
kind: ConfigMap
metadata:
  name: softw-config
  namespace: softw-practice
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: shopping_platform
  DB_USER: softw
  JWT_EXPIRES_IN: 30d
  CORS_ORIGIN: "http://localhost:30080,http://softw.local"
  RATE_LIMIT_MAX: "300"
